#!/bin/bash
#
# bootstrap
#
# Checks for dependencies so you can get rolling with ActiveCell straight away

echo ""
echo "tabestakes.js"
echo "A bad-ass interactive grid platform."
echo ""

#
# Check for npm
#
if test ! $(which npm); then
  echo "  x You need to install npm. If you use Homebrew, you can run:"
  echo "    brew install npm"
  exit
else
  echo "  + npm found."
fi

#
# Install from package file
#
echo ""
echo "Installing packages from package.json."
npm install
