describe 'integration', ->
  require './base'
  require './custom_classes'
  require './editable'
  require './nested'
  require './nested_editable'
  require './filterable'
  require './deletable'
  require './resizable'
  require './hierarchy_drag'
  require './reorder_drag'
  require './custom_editor'
  # require './full_stack'
